### PR TITLE
Fix error when space in bin path

### PR DESCRIPTION
**Pull request by marob**
In response of https://github.com/kevva/bin-wrapper/pull/43

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'm very wary of changing stuff in this module as any change seems to break someones use-case...

See history: https://github.com/sindresorhus/bin-version/commits/master

Can you please test this on Windows to make sure it doesn't break anything?

**Comment by marob** [comment]
My PR works as follow:
* if the "bin" param is a command available in the PATH (example: ``binVersion('npm', ...)``), it changes nothing (compared to the current version)
* if the "bin" param is a path to a binary file **without space** in the path (example: ``binVersion('/path/to/bin/executable.sh', ...)`` or ``binVersion('C:\\path\\to\\bin\\executable.bat', ...)``), it changes nothing (compared to the current version)
* if the "bin" param is a path to a binary file **with space** in the path (example: ``binVersion('/path/with space/to/bin/executable.sh', ...)`` or ``binVersion('C:\\path\\with space\\to\\bin\\executable.bat', ...)``), it escapes the param
  * under Unix, it escapes spaces with ``\``
  * under Windows, it escapes the path by wrapping it in double quotes

I think it should not break modules depending on bin-version.

FYI, I initially created this PR to fix https://github.com/imagemin/optipng-bin/issues/45. But I only discovered this issue after my PR.

**Comment by marob** [comment]
I've added some documentation in the usage section of the README

**Comment by sindresorhus** [comment]
Thanks, but ended up doing a proper fix :)

**Pull request closed without merging**
